name: Generate Snake

on:
  schedule:
    # Run at 12am UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: peregrinno
          gif_out_path: dist/snake.gif
      - uses: actions/upload-artifact@v2
        with:
          name: snake-gif
          path: dist/snake.gif
      - name: Push Snake Animation to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          commit_message: "Add Snake animation"
          directory: dist
